version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    hostname: postgres
    env_file:
      - ./db/db.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - todo

  back:
    build:
      context: ./back/
      dockerfile: Dockerfile
      args:
        PG_USER: todo
        PG_PASS: todo
        PG_HOST: postgres
    container_name: todo-back
    restart: unless-stopped
    hostname: back
    working_dir: /var/www
    ports:
      - 3001:3001
    depends_on:
      - postgres
    networks:
      - todo

  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
      args:
        BACKEND: http://back:3001
    container_name: todo-front
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - back
    networks:
      - todo

networks:
  todo:
    driver: bridge

volumes:
  postgres-db:
