version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    hostname: postgres
    env_file:
      - ./db/db.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    deploy:
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  back:
    build:
      context: ./back/
      dockerfile: Dockerfile
      args:
        PG_USER: todo
        PG_PASS: todo
        PG_HOST: postgres
    image: localhost:5000/back
    container_name: todo-back
    restart: unless-stopped
    hostname: back
    working_dir: /var/www
    ports:
      - 3001:3001
    depends_on:
      - postgres
    deploy:
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
      args:
        BACKEND: http://back:3001
    image: localhost:5000/front
    container_name: todo-front
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - back
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  nest:
    build:
      context: ./nest/
      dockerfile: Dockerfile
      args:
        PG_USER: todo
        PG_PASS: todo
        PG_HOST: postgres
    image: localhost:5000/nest
    container_name: todo-nest
    restart: unless-stopped
    hostname: back
    working_dir: /var/www
    ports:
      - 3001:3001
    depends_on:
      - postgres
    deploy:
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  go:
    build:
      context: ./go/
      dockerfile: Dockerfile
      args:
        PG_USER: todo
        PG_PASS: todo
        PG_HOST: postgres
    image: localhost:5000/go
    container_name: todo-go
    restart: unless-stopped
    hostname: back
    working_dir: /var/www
    ports:
      - 3001:3001
    depends_on:
      - postgres
    deploy:
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  postgres-db:
